### ISSUE TITLE
Tinymce can't embed iframe video

### ISSUE THREAD

**Issue by puttpotsawee** [neokoenig/jQuery-gridmanager#78]
Hi, I've been trying on gridManager with TinyMCE for a while, It worked so well, and it's really great!

Now, i'd like to extend my gridmanager to be able to insert video.
I know that TinyMCE worked really great on that using the TinyMCE's internal plugin called 'media'
However, using TinyMCE's media on gridmanager canvans doesn't seem to work.

I tried with the demon on: [here](https://neokoenig.github.io/jQuery-gridmanager/demo/tinymce.html)

after pasting iframe video on tinyMCE it appears (from the inspection)

``` html
<img class="mce-object mce-object-iframe img-responsive" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" width="560" height="315" data-mce-p-allowfullscreen="allowfullscreen" data-mce-p-frameborder="0" data-mce-p-src="https://www.youtube.com/embed/T3e5sAAViWk?rel=0&amp;controls=0&amp;showinfo=0" data-mce-object="iframe">
```

instead of rendering iframe dom on the grid canvas

**Comment by neokoenig** [comment]
So tinyMCE renders the iFrame as a graphic placeholder (which presumably gets reinterpreted on TinyMCE's cleanup process) however, gridmanager just sees the graphic/image and doesn't run any tinyMCE methods to reinterpret the graphic.

TBH, this is expected behaviour; really, you want tinyMCE to not touch the iframe at all and just render it natively. How you turn that off in tinyMCE though I have no idea...

**Comment by puttpotsawee** [comment]
I got it! You are right, tinyMCE forcefully put `<iframe>` to an image placeholder.

However, on TinyMCE 4.3, there's an option to disable it, making the iframe become live from the editor
Just upgrade TinyMCE and i got it right
[refer to this](https://www.tinymce.com/docs/plugins/media/#media_live_embeds)
